apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-67mx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-majj-tenant/rhtap-demo-app/hacbs-test-project-67mx@sha256:b4ee2765bf1e3dd6c53d8549c7ce0136c9a8ee0fe3f01411e6174558055e23ad
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
